# Generated by Django 3.1.14 on 2025-06-21 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_auto_20250621_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='defense',
            new_name='defence',
        ),
    ]
